Updating

diff --git a/split-diff/split-diff 2 b/split-diff/split-diff 2
--- a/split-diff/split-diff 2
+++ b/split-diff/split-diff 2
@@ -1,91 +1,178 @@
-// Colors
+# Maintainer: Brenton Horne <brentonhorne77 at gmail dot com>
 
-@text-color: #aaa;
-@text-color-subtle: #555;
-@text-color-highlight: #fff;
-@text-color-selected: @text-color-highlight;
+_pkgname=atom
+_version=fusion
 
-@text-color-info: #5293d8;
-@text-color-success: #2BDA77;
-@text-color-warning: #ff982d;
-@text-color-error: #c00;
+# Module Versions
+_about_url="https://github.com/fusion809/about"
+_about_arch_ver=1.5.16
+_atom_typescript_ver=8.10.2
+_browser_plus_fix_ver=0.1.3
+_dark_bint_syntax_ver=0.8.4
+_electron_ver=0.36.12
+_file_icons_ver=1.7.13
+_fusion_ui_ver=0.10.3
+_git_plus_ver=5.14.0
+_git_time_machine_ver=1.5.3
+_language_asciidoc2_ver=1.5.0
+_language_asciidoc2_url="https://github.com/fusion809/language-asciidoc2"
+_language_d_ver=3.2.3
+_language_docker_ver=1.1.6
+_language_fortran_ver=2.0.11
+_language_gentoo_ver=0.9.0
+_language_gfm2_ver=0.90.3
+_language_groovy_ver=0.6.0
+_language_haskell_ver=1.7.15
+_language_ini2_ver=1.17.2
+_language_ini2_url="https://github.com/fusion809/language-ini2"
+_language_julia_ver=0.6.0
+_language_liquid_ver=0.5.1
+_language_lisp_ver=0.2.0
+_language_lua_ver=0.9.4
+_language_matlab_ver=0.2.1
+_language_pascal_ver=0.18.1
+_language_patch2_url="https://github.com/fusion809/language-patch2"
+_language_patch2_ver=0.1.3
+_language_rpm_spec2_ver=0.9.2
+_language_rpm_spec2_url="https://github.com/fusion809/language-rpm-spec2"
+_language_viml_ver=1.0.0
+_language_shellscript_ver=0.22.3
+_markdown_scroll_sync_ver=2.1.2
+_markdown_toc_ver=0.4.1
+_minimap_ver=4.24.3
+_nuclide_ver=0.139.0
+_package_sync_ver=1.1.0
+_pigments_ver=0.29.0
+_script_ver=3.7.3
+_platformio_ide_terminal_ver=2.0.10
 
-@text-color-ignored: @text-color-subtle;
-@text-color-added: @text-color-success;
-@text-color-renamed: @text-color-info;
-@text-color-modified: @text-color-warning;
-@text-color-removed: @text-color-error;
+pkgname=${_pkgname}-editor-${_version}
+pkgver=1.7.4
+pkgrel=9
+pkgdesc='Hackable text editor for the 21st Century, based on web technologies with several custom packages installed.'
+arch=('x86_64' 'i686')
+url="https://github.com/${_pkgname}/${_pkgname}"
+license=('MIT')
+depends=('alsa-lib' 'desktop-file-utils' 'gconf' 'gtk2' 'libgnome-keyring' 'libnotify' 'libxtst' 'nodejs' 'nss' 'python2')
+optdepends=('gvfs: file deletion support')
+makedepends=('git' 'npm')
+conflicts=('atom-editor-bin' 'atom-editor')
+install=${_pkgname}-${_version}.install
+source=("${_pkgname}-${pkgver}.tar.gz::$url/archive/v${pkgver}.tar.gz"
+"about-arch-${_about_arch_ver}.tar.gz::$_about_url/archive/v${_about_arch_ver}.tar.gz"
+"${_pkgname}.desktop"
+"${_pkgname}")
+sha256sums=('6ef3bb4c2fea85a7d1c7665fef8aac4e353c8f8da5e2878fea3aecf5437383d4'
+            '1f9d3d560ab6374b38644e9c55a7c8fa0f8f581758fb2ee0b18c3f8c53aee44f'
+            'fb6527d029c5edffa89a5085cc1d3eaaa892e18cc2aefa8ce855be7612da4788'
+            '0b3e189202c82c98bc3d3f9a9c88d2aab88537cdd2e0fc2f4d537f55a068acb5')
 
-@background-color-info: #0098ff;
-@background-color-success: #17ca65;
-@background-color-warning: #ffaa2c;
-@background-color-error: #c00;
-@background-color-highlight: rgba(255, 255, 255, 0.07);
-@background-color-selected: #4182C4;
+prepare() {
+  cd "$srcdir/${_pkgname}-$pkgver"
 
-@app-background-color: #333;
+  ## package.json edits
+  sed -i -e "/exception-reporting/d" \
+         -e "/metrics/d" package.json
 
-@base-background-color: lighten(@tool-panel-background-color, 5%);
-@base-border-color: rgba(0, 0, 0, 0.5);
+  sed -i -e "s/\"about\": \".*\"/\"about-arch\": \"${_about_arch_ver}\"/g" package.json # switching about with about-arch
 
-@pane-item-background-color: @base-background-color;
-@pane-item-border-color: rgba(0, 0, 0, 0.5);
+  sed -i -e "s/\"electronVersion\": \".*\"/\"electronVersion\": \"${_electron_ver}\"/g" package.json              # change electron ver
 
-@input-background-color: #212224;
-@input-border-color: @base-border-color;
+  sed -i -e "/\"atom-light-syntax\": \".*\"/a \
+              \"dark-bint-syntax\": \"${_dark_bint_syntax_ver}\"," package.json # install dark-bint-syntax
 
-@tool-panel-background-color: #1d1f21;
-@tool-panel-border-color: @base-border-color;
+  sed -i -e "/\"atom-light-ui\": \".*\",/a \
+             \"fusion-ui\": \"${_fusion_ui_ver}\"," package.json # install fusion-ui theme
 
-@inset-panel-background-color: #161719;
-@inset-panel-border-color: @base-border-color;
+  sed -i -e "/\"find-and-replace\": \".*\",/i \
+              \"file-icons\": \"${_file_icons_ver}\"," package.json # file-icons
 
-@panel-heading-background-color: #43484d;
-@panel-heading-border-color: fadein(@base-border-color, 10%);
+  sed -i -e "/\"git-diff\": \".*\",/a \
+              \"git-plus\": \"${_git_plus_ver}\",\n    \"git-time-machine\": \"${_git_time_machine_ver}\"," package.json # git packages
 
-@overlay-background-color: #202123;
-@overlay-border-color: @background-color-highlight;
+  sed -i -e "/\"language-c\": \".*\",/i \
+              \"language-asciidoc2\": \"${_language_asciidoc2_ver}\"," package.json
 
-@button-background-color: #43484d;
-@button-background-color-hover: lighten(@button-background-color, 5%);
-@button-background-color-selected: #5c6064;
-@button-border-color: @base-border-color;
+  sed -i -e "/\"language-css\": \".*\",/a \
+              \"language-d\": \"${_language_d_ver}\",\n    \"language-docker\": \"${_language_docker_ver}\",\n    \"language-fortran\": \"${_language_fortran_ver}\"," package.json
 
-@tab-bar-background-color: #222;
-@tab-bar-border-color: darken(@tab-background-color-active, 10%);
-@tab-background-color: #333;
-@tab-background-color-active: #222;
-@tab-border-color: #484848;
+  sed -i -e "s/\"language-gfm\": \".*\",/\"language-gfm2\": \"${_language_gfm2_ver}\",/g" package.json # GFM2
 
-@tree-view-background-color: rgba(255,255,100,0.05);
-@tree-view-border-color: @tool-panel-border-color;
+  sed -i -e "/\"language-gfm2\": \".*\",/i \
+              \"language-gentoo\": \"${_language_gentoo_ver}\"," package.json # gentoo
 
-@scrollbar-background-color: #222425; // Needs to be opaque -> atom/atom/issues/4578
-@scrollbar-color: rgba(92, 92, 92, 0.5);
+  sed -i -e "/\"language-hyperlink\": \".*\",/a \
+              \"language-ini2\": \"${_language_ini2_ver}\",\n    \"language-julia\": \"${_language_julia_ver}\"," package.json # Julia
 
-@ui-site-color-1: @background-color-success; // green
-@ui-site-color-2: @background-color-info; // blue
-@ui-site-color-3: @background-color-warning; // orange
-@ui-site-color-4: #db2ff4; // purple
-@ui-site-color-5: #f5e11d; // yellow
+  sed -i -e "/\"language-less\": \".*\",/a \
+              \"language-liquid\": \"${_language_liquid_ver}\",\n    \"language-lisp\": \"${_language_lisp_ver}\",\n    \"language-lua\": \"${_language_lua_ver}\"," package.json # Add Liquid, Lisp, Lua
 
+  sed -i -e "/\"language-makefile\": \".*\",/a \
+              \"language-matlab\": \"${_language_matlab_ver}\"," package.json # MATLAB
 
-// Sizes
+  sed -i -e "/\"language-perl\": \".*\",/i \
+              \"language-pascal\": \"${_language_pascal_ver}\",\n    \"language-patch2\": \"${_language_patch2_ver}\"," package.json # pascal
 
-@font-size: 11px;
-@input-font-size: 14px;
+  sed -i -e "/\"dependencies\": {/a \
+              \"language-patch2\": \"${_language_patch2_url}\"," package.json
 
-@disclosure-arrow-size: 12px;
+  sed -i -e "/\"dependencies\": {/a \
+              \"language-asciidoc2\": \"${_language_asciidoc2_url}\",\n    \"language-ini2\": \"${_language_ini2_url}\",\n    \"language-patch2\": \"${_language_patch2_ver}\",\n    \"language-rpm-spec2\": \"${_language_rpm_spec2_url}\"," package.json
 
-@component-padding: 10px;
-@component-icon-padding: 5px;
-@component-icon-size: 16px;
-@component-line-height: 25px;
-@component-border-radius: 2px;
+  sed -i -e "/\"language-toml\": \".*\",/a \
+              \"language-viml\": \"${_language_viml_ver}\"," package.json   # Add VimL
 
-@tab-height: 26px;
+  sed -i -e "s/\"language-shellscript\": \".*\"/\"language-shellscript\": \"${_language_shellscript_ver}\"/g" package.json
 
+  sed -i -e "/\"language-shellscript\": \".*\",/i \
+              \"language-rpm-spec2\": \"${_language_rpm_spec2_ver}\"," package.json
 
-// Other
+  sed -i -e "/\"package-generator\": \".*\",/a \
+              \"package-sync\": \"${_package_sync_ver}\",\n    \"pigments\": \"${_pigments_ver}\",\n    \"script\": \"${_script_ver}\",\n    \"platformio-ide-terminal\": \"${_platformio_ide_terminal_ver}\"," package.json
 
-@font-family: 'Lucida Grande', 'Segoe UI', Ubuntu, Cantarell, sans-serif;
+  sed -i -e "/\"markdown-preview\": \".*\",/a \
+              \"markdown-scroll-sync\": \"${_markdown_scroll_sync_ver}\",\n    \"markdown-toc\": \"${_markdown_toc_ver}\",\n    \"minimap\": \"${_minimap_ver}\"," package.json
+
+ sed -i -e "/\"bracket-matcher\": \".*\",/a \
+              \"browser-plus-fix\": \"${_browser_plus_fix_ver}\"," package.json
+
+ sed -i -e "s|^\"|    \"|g"  package.json # fixing spacing issues
+
+ chmod 755 -R package.json
+
+ sed -i -e 's@node script/bootstrap@node script/bootstrap --no-quiet@g' \
+ ./script/build || die "Fail fixing verbosity of script/build"
+
+ if ! [[ -d node_modules ]]; then
+  mkdir -p node_modules
+ else
+   rm -rf node_modules/about-arch
+   rm -rf node_modules/language-asciidoc2
+   rm -rf node_modules/language-rpm-spec
+ fi
+
+  mv $srcdir/about-${_about_arch_ver} $srcdir/about-arch
+  mv $srcdir/about-arch node_modules
+  sed -i -e "s/atom-editor/atom-editor-${_version}/g" node_modules/about-arch/lib/about-view.coffee
+  sed -i -e "s/<%=Desc=%>/$pkgdesc/g" ${srcdir}/${_pkgname}.desktop
+}
+
+build() {
+  cd "$srcdir/${_pkgname}-$pkgver"
+  export PYTHON=/usr/bin/python2
+  until ./script/build --build-dir "$srcdir/${_pkgname}-build"; do :; done
+}
+
+package() {
+  cd "$srcdir/${_pkgname}-$pkgver"
+
+  script/grunt install --build-dir "$srcdir/${_pkgname}-build" --install-dir "$pkgdir/usr"
+
+  install -Dm755 "$srcdir/${_pkgname}" "$pkgdir/usr/bin/${_pkgname}"
+
+  rm "$pkgdir/usr/share/applications/${_pkgname}.desktop"
+
+  install -Dm644 "$srcdir/${_pkgname}.desktop" "$pkgdir/usr/share/applications/${_pkgname}.desktop"
+  install -Dm644 "resources/app-icons/stable/png/1024.png" "$pkgdir/usr/share/pixmaps/${_pkgname}.png"
+  install -Dm644 "LICENSE.md" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.md"
+}
